spring:
  application:
    name: LLM-Spring-Client
  main:
    allow-circular-references: true
  ai:
    ollama:
      base-url: http://localhost:11431
      chat:
        model: gemma3:4b-it-q4_K_M
  datasource:
    url: jdbc:postgresql://localhost:5432/ragdb
    username: ${USERNAME:postgres}
    password: ${PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
